'use client';
import { Suspense, useEffect, useState } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import { FileDropZone } from '@/components/FileDropZone';
import { Card } from '@/components/Card';
import { Button } from '@/components/Button';

function VerifyContent() {
  const params = useSearchParams();
  const router = useRouter();
  const evidenceId = params.get('evidenceId');
  const tamperMethod = params.get('tamperMethod');

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [autoTriggered, setAutoTriggered] = useState(false);

  useEffect(() => {
    if (!evidenceId || !tamperMethod || autoTriggered) return;

    setAutoTriggered(true);
    setLoading(true);
    setError(null);

    const form = new FormData();
    form.append('evidenceId', evidenceId);
    form.append('tamperMethod', tamperMethod);

    fetch('/api/verify', { method: 'POST', body: form })
      .then(async (res) => {
        if (!res.ok) {
          const errData = await res.json();
          throw new Error(errData.error || 'Verification failed');
        }
        return res.json();
      })
      .then((result) => {
        sessionStorage.setItem('verifyResult', JSON.stringify(result));
        router.push('/verify/result');
      })
      .catch((err: any) => {
        setError(err.message);
        setLoading(false);
      });
  }, [evidenceId, tamperMethod, autoTriggered, router]);

  const handleFile = async (file: File) => {
    setLoading(true);
    setError(null);
    try {
      const form = new FormData();
      form.append('image', file);
      const res = await fetch('/api/verify', { method: 'POST', body: form });
      if (!res.ok) {
        const errData = await res.json();
        throw new Error(errData.error || 'Verification failed');
      }
      const result = await res.json();
      sessionStorage.setItem('verifyResult', JSON.stringify(result));
      router.push('/verify/result');
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-8">
      <div>
        <h1>Verify Image</h1>
        <p className="text-lg text-mist mt-2 font-[family-name:var(--font-sans)]">
          Upload a signed or tampered image to check its C2PA manifest and evidence record status.
        </p>
      </div>

      {evidenceId && tamperMethod && (
        <Card>
          <p className="text-sm text-ink font-[family-name:var(--font-sans)]">
            Verifying tampered image for record <strong>{evidenceId}</strong> using method <strong>{tamperMethod}</strong>...
          </p>
        </Card>
      )}

      {(!evidenceId || !tamperMethod) && (
        <FileDropZone onFile={handleFile} label="Drop signed or tampered image here or click to browse" />
      )}

      {loading && <p className="text-mist text-sm">Verifying image...</p>}
      {error && <p className="text-red-600 text-sm font-semibold">{error}</p>}

      <Card>
        <h3>How it works</h3>
        <ol className="list-decimal list-inside mt-4 space-y-2 text-sm text-ink font-[family-name:var(--font-sans)]">
          <li>Upload an image that was previously signed with a C2PA manifest</li>
          <li>The verifier extracts and validates the C2PA manifest</li>
          <li>If the image was tampered with, the verifier reports the discrepancy</li>
          <li>Known tampered files generated by this lab are matched by hash and the tamper method is reported</li>
        </ol>
      </Card>
    </div>
  );
}

export default function VerifyPage() {
  return (
    <Suspense fallback={<p className="text-mist">Loading...</p>}>
      <VerifyContent />
    </Suspense>
  );
}
